import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const out = 'test-results'; await mkdir(out, { recursive: true });
const APP_URL = process.env.QA_URL || 'http://127.0.0.1:4173/';
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--autoplay-policy=no-user-gesture-required'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['camera', 'microphone'], acceptDownloads: true });
const page = await context.newPage(); const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', msg => { if (msg.type() === 'error') console.log('console error:', msg.text().slice(0,250)); });
await page.goto(APP_URL);
for (const [name, width, height] of [['desktop',1440,900],['tablet',768,1024],['mobile',375,812],['narrow',320,568]]) {
  await page.setViewportSize({ width,height });
  await page.screenshot({ path:`${out}/camera-${name}.png`, fullPage:true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true, `${name} has no horizontal overflow`);
  await page.getByRole('button',{name:'Install app',exact:true}).click();
  await page.screenshot({ path:`${out}/install-${name}.png`,fullPage:true });
  await page.getByRole('button',{name:'Close',exact:true}).click();
}
await page.setViewportSize({ width:375,height:812 });
await page.getByRole('button',{name:'Open camera',exact:true}).click();
await page.getByRole('button',{name:'Start recording',exact:true}).waitFor({timeout:60000});
await page.getByRole('button',{name:'Start',exact:true}).waitFor();
await page.waitForFunction(() => !document.querySelector('.calibration-row button')?.disabled, {timeout:90000});
console.log('camera and all three MediaPipe models ready');
await page.getByRole('button',{name:'Nose pinch — Pinch your nose shut',exact:true}).click();
await page.screenshot({path:`${out}/camera-active-mobile.png`,fullPage:true});
const before = await page.locator('canvas').evaluate(c=>c.toDataURL());
await page.waitForTimeout(400);
assert.notEqual(await page.locator('canvas').evaluate(c=>c.toDataURL()),before,'camera frames update');
await page.getByRole('button',{name:'Start recording',exact:true}).click();
await page.waitForTimeout(2500);
await page.screenshot({path:`${out}/recording-mobile.png`,fullPage:true});
await page.getByRole('button',{name:'Stop recording',exact:true}).click();
await page.getByRole('button',{name:'Save Video',exact:true}).waitFor();
await page.locator('.review-video').evaluate(v=>v.play());
await page.waitForFunction(()=>document.querySelector('.review-video').currentTime>.2);
assert.equal(await page.locator('.capture-source').evaluate(v=>v.srcObject===null),true,'camera released after recording');
for (const [name,width,height] of [['desktop',1440,900],['tablet',768,1024],['mobile',375,812],['narrow',320,568]]) {
  await page.setViewportSize({width,height}); await page.screenshot({path:`${out}/review-${name}.png`,fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
}
const downloadPromise = page.waitForEvent('download');
await page.getByRole('button',{name:'Download video',exact:true}).click();
const download = await downloadPromise; await download.saveAs(`${out}/${download.suggestedFilename()}`);
console.log('recording playable and saved:',download.suggestedFilename());
await page.getByRole('button',{name:'Retake',exact:true}).click();
await page.getByRole('button',{name:'Start recording',exact:true}).waitFor({timeout:30000});
await page.getByRole('button',{name:'Switch camera',exact:true}).click();
await page.getByRole('button',{name:'Start recording',exact:true}).waitFor({timeout:30000});
await page.getByRole('button',{name:'Turn mic off',exact:true}).click();
await page.getByRole('button',{name:'Start recording',exact:true}).click();
await page.waitForTimeout(1500);
await page.getByRole('button',{name:'Stop recording',exact:true}).click();
await page.getByRole('button',{name:'Save Video',exact:true}).waitFor();
assert.equal(await page.getByText('No sound',{exact:true}).count(),1);
console.log('camera switching, retake and silent recording passed');
await page.getByRole('button',{name:'Retake',exact:true}).click();
await page.getByRole('button',{name:'Record new',exact:true}).click();
await page.getByRole('button',{name:'Start recording',exact:true}).waitFor();
await page.getByRole('button',{name:'Start recording',exact:true}).click();
await page.waitForTimeout(1200);
await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));
await page.getByRole('button',{name:'Save Video',exact:true}).waitFor();
console.log('interrupted recording recovers to review');
assert.deepEqual(errors,[]);
await writeFile(`${out}/qa.json`,JSON.stringify({passed:true,errors,checked:['responsive camera/install/review','real MediaPipe load','fake camera and mic','recording playback and download','switch camera','silent clip','interruption']},null,2));
await context.close();
const denied = await browser.newContext(); const deniedPage=await denied.newPage();
await deniedPage.addInitScript(()=>{ navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('denied','NotAllowedError')}; });
await deniedPage.goto(APP_URL); await deniedPage.getByRole('button',{name:'Open camera',exact:true}).click();
await deniedPage.getByRole('alert').filter({hasText:'denied'}).waitFor();
assert.equal(await deniedPage.getByRole('button',{name:'Open camera',exact:true}).isEnabled(),true);
console.log('camera-denial recovery passed');
await denied.close(); await browser.close();
